version: '3.9'
services:
  ai:
    build:
      context: ./apps/ai
    container_name: lumo-ai
    env_file:
      - ./apps/ai/.env
    ports:
      - '8000:8000'
    restart: unless-stopped

  # server:
  #   build:
  #     context: ./apps/server
  #   container_name: lumo-server
  #   env_file:
  #     - ./apps/server/.env
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - ai
